sudo: false
language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6.0

git:
  depth: 3

env:
  global:
    # $TRANSIFEX_PASSWORD for oscar_bot (used in transifex.sh)
    # - secure: FuIlzEsGJiAwhaIRBmRNsq9eXmuzs25fX6BChknW4lDyVAySWMp0+Zps9Bd0JgfFYUG3Ip+OTmksYIoTUsG25ZJS9cq1IFt3QKUAN70YCI/4ZBLeIdICPEyxq+Km179+NeEXmBUug17RLMLxh3MWfO+RKUHK9yHIPNNpq0dNyoo=
    # These two environment variables could be set by Travis itself, or Travis
    # could configure itself in /etc/, ~/, or inside of the virtual
    # environments. In any case if these two values get configured then end
    # users only need to enable the pip cache and manually run pip wheel before
    # running pip install.
    # - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    # - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

    DJANGO_SETTINGS_MODULE=settings

#before_cache:
#  - rm -rf $HOME/.cache/pip/log


#cache:
#  directories:
#    - $HOME/.cache/pip


install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pycodestyle . --ignore=E501,E402
  # - pep8
  - python ./manage.py thumbnail clear
  - python ./manage.py collectstatic --noinput

  - python ./manage.py test
  #- pytest
